//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgettoMalnati.Properties {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DatiTest {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DatiTest() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProgettoMalnati.Properties.DatiTest", typeof(DatiTest).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a INSERT INTO utenti(nome, password, path_monitorato) VALUES (&apos;tizio&apos;, &apos;abbecedario&apos;,&apos;C:\\user\\Documents&apos;);.
        /// </summary>
        internal static string String01 {
            get {
                return ResourceManager.GetString("String01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a INSERT INTO utenti(nome, password, path_monitorato) VALUES (&apos;caio&apos;, &apos;abbecedario&apos;,&apos;C:\\user\\Documents&apos;);.
        /// </summary>
        internal static string String02 {
            get {
                return ResourceManager.GetString("String02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a INSERT INTO utenti(nome, password, path_monitorato) VALUES (&apos;sempronio&apos;, &apos;abbecedario&apos;,&apos;C:\\user\\Documents&apos;);.
        /// </summary>
        internal static string String03 {
            get {
                return ResourceManager.GetString("String03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a INSERT INTO utenti(nome, password, path_monitorato) VALUES (&apos;cesare&apos;, &apos;abbecedario&apos;,&apos;C:\\user\\Documents&apos;);.
        /// </summary>
        internal static string String04 {
            get {
                return ResourceManager.GetString("String04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a INSERT INTO fileutente(nome_utente, nome_file_c, path_relativo_c) VALUES (&apos;tizio&apos;, &apos;cose_importanti.txt&apos;, &apos;.&apos;).
        /// </summary>
        internal static string String05 {
            get {
                return ResourceManager.GetString("String05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a INSERT INTO fileutente(nome_utente, nome_file_c, path_relativo_c) VALUES (&apos;tizio&apos;, &apos;cose_importanti.txt&apos;, &apos;Scuola&apos;).
        /// </summary>
        internal static string String06 {
            get {
                return ResourceManager.GetString("String06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a INSERT INTO fileutente(nome_utente, nome_file_c, path_relativo_c) VALUES (&apos;tizio&apos;, &apos;robette.exe&apos;, &apos;Scuola&apos;).
        /// </summary>
        internal static string String07 {
            get {
                return ResourceManager.GetString("String07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a INSERT INTO fileutente(nome_utente, nome_file_c, path_relativo_c) VALUES (&apos;tizio&apos;, &apos;non_aprire.dll&apos;, &apos;Scuola\\Programmi&apos;).
        /// </summary>
        internal static string String08 {
            get {
                return ResourceManager.GetString("String08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a INSERT INTO fileutente(nome_utente, nome_file_c, path_relativo_c) VALUES (&apos;caio&apos;, &apos;robette.exe&apos;, &apos;.&apos;).
        /// </summary>
        internal static string String09 {
            get {
                return ResourceManager.GetString("String09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a INSERT INTO fileutente(nome_utente, nome_file_c, path_relativo_c) VALUES (&apos;caio&apos;, &apos;1234&apos;, &apos;lkjhgfd&apos;).
        /// </summary>
        internal static string String10 {
            get {
                return ResourceManager.GetString("String10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a INSERT INTO fileutente(nome_utente, nome_file_c, path_relativo_c) VALUES (&apos;caio&apos;, &apos;liste.lst&apos;, &apos;mnbvdt\\fgvcdr&apos;).
        /// </summary>
        internal static string String11 {
            get {
                return ResourceManager.GetString("String11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a INSERT INTO fileutente(nome_utente, nome_file_c, path_relativo_c) VALUES (&apos;caio&apos;, &apos;parcella.doc&apos;, &apos;Economica&apos;).
        /// </summary>
        internal static string String12 {
            get {
                return ResourceManager.GetString("String12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a INSERT INTO fileutente(nome_utente, nome_file_c, path_relativo_c) VALUES (&apos;sempronio&apos;, &apos;doc1.doc&apos;, &apos;.&apos;).
        /// </summary>
        internal static string String13 {
            get {
                return ResourceManager.GetString("String13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a INSERT INTO fileutente(nome_utente, nome_file_c, path_relativo_c) VALUES (&apos;sempronio&apos;, &apos;robette.exe&apos;, &apos;Altro&apos;).
        /// </summary>
        internal static string String14 {
            get {
                return ResourceManager.GetString("String14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a INSERT INTO fileutente(nome_utente, nome_file_c, path_relativo_c) VALUES (&apos;sempronio&apos;, &apos;doc2.doc&apos;, &apos;Cose&apos;).
        /// </summary>
        internal static string String15 {
            get {
                return ResourceManager.GetString("String15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a INSERT INTO snapshots(sha_contenuto,dim,nome_locale_s, id_file) VALUES (&apos;1f8a690b7366a2323e2d5b045120da7e93896f47&apos;,0, &apos;x1&apos;, 4).
        /// </summary>
        internal static string String16 {
            get {
                return ResourceManager.GetString("String16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a INSERT INTO fileutente(nome_utente, nome_file_c, path_relativo_c) VALUES (&apos;cesare&apos;, &apos;armate.xls&apos;, &apos;Utilita&apos;).
        /// </summary>
        internal static string String17 {
            get {
                return ResourceManager.GetString("String17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a INSERT INTO fileutente(nome_utente, nome_file_c, path_relativo_c) VALUES (&apos;cesare&apos;, &apos;colosseo.jpg&apos;, &apos;Scuola&apos;).
        /// </summary>
        internal static string String18 {
            get {
                return ResourceManager.GetString("String18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a INSERT INTO snapshots(sha_contenuto,dim,nome_locale_s,id_file) VALUES (&apos;1f8a690b7366a2323e2d5b045120da7e93896f47&apos;,0, &apos;x3&apos;,4).
        /// </summary>
        internal static string String19 {
            get {
                return ResourceManager.GetString("String19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a INSERT INTO snapshots(sha_contenuto,dim,nome_locale_s, id_file) VALUES (&apos;1f8a690b7366a2323e2d5b045120da7e93896f47&apos;,17, &apos;x2&apos;, 4).
        /// </summary>
        internal static string String20 {
            get {
                return ResourceManager.GetString("String20", resourceCulture);
            }
        }
    }
}
