//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clientWPF.Properties {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messaggi {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messaggi() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("clientWPF.Properties.Messaggi", typeof(Messaggi).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &quot;Il collegamento dati non può essere istanziato. Riprovare più tardi&quot;.
        /// </summary>
        public static string collegamentoDati {
            get {
                return ResourceManager.GetString("collegamentoDati", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &quot;La dimensione o l&apos;hash del file proveniente dal server non corrispondono al file scaricato&quot;.
        /// </summary>
        public static string datiInconsistenti {
            get {
                return ResourceManager.GetString("datiInconsistenti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &quot;La connessione con il server si è interrotta. Riprovare&quot;.
        /// </summary>
        public static string erroreConnessioneServer {
            get {
                return ResourceManager.GetString("erroreConnessioneServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &quot;Un errore sconosciuto è accaduto sul server. Riprovare più tardi&quot;.
        /// </summary>
        public static string erroreServer {
            get {
                return ResourceManager.GetString("erroreServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &quot;Il file esiste già sul server. Forse lo vuoi solo aggiornare?&quot;.
        /// </summary>
        public static string fileEsistente {
            get {
                return ResourceManager.GetString("fileEsistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &quot;Il formato dei dati forniti è errato. Riprovare&quot;.
        /// </summary>
        public static string formatoDatiErrato {
            get {
                return ResourceManager.GetString("formatoDatiErrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &quot;L&apos;utente ha troppi file memorizzati sul server. Dividere la cartella e creare un nuovo account.&quot;.
        /// </summary>
        public static string limiteFileSuperato {
            get {
                return ResourceManager.GetString("limiteFileSuperato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &quot;L&apos;azione richiesta non può essere gestita ora.&quot;.
        /// </summary>
        public static string momentoSbagliato {
            get {
                return ResourceManager.GetString("momentoSbagliato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &quot;Il nome utente scelto è già in uso.&quot;.
        /// </summary>
        public static string nomeUtenteInUso {
            get {
                return ResourceManager.GetString("nomeUtenteInUso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &quot;Prima di lanciare un comando è necessario essersi loggati con il comando login.&quot;.
        /// </summary>
        public static string nonLoggato {
            get {
                return ResourceManager.GetString("nonLoggato", resourceCulture);
            }
        }
    }
}
