//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clientWPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SQLquery {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SQLquery() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("clientWPF.Properties.SQLquery", typeof(SQLquery).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select valido from file where nome_file_c = @nome_file and path_relativo_c = @path;.
        /// </summary>
        internal static string getFileValidity {
            get {
                return ResourceManager.GetString("getFileValidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to insert into versioni(id_file,timestamp_vers) VALUES (@id_file, @timestamp_vers);.
        /// </summary>
        internal static string sqlAddVersion {
            get {
                return ResourceManager.GetString("sqlAddVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT id FROM file WHERE valido = &apos;FALSE&apos;;.
        /// </summary>
        internal static string sqlGetDeletedIds {
            get {
                return ResourceManager.GetString("sqlGetDeletedIds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT nome_file_c, path_relativo_c, t_creazione,  t_modifica, sha_contenuto, dim, valido FROM file WHERE id = @id_file;.
        /// </summary>
        internal static string sqlGetFileData {
            get {
                return ResourceManager.GetString("sqlGetFileData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT id FROM file WHERE valido = &apos;TRUE&apos;;.
        /// </summary>
        internal static string sqlGetId {
            get {
                return ResourceManager.GetString("sqlGetId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT timestamp_vers FROM versioni WHERE id_file = @id_file ;.
        /// </summary>
        internal static string sqlGetVersionData {
            get {
                return ResourceManager.GetString("sqlGetVersionData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO file (nome_file_c, path_relativo_c, dim, t_modifica, t_creazione, sha_contenuto) VALUES(@nome_file, @path, @dim, @t_modifica, @t_creazione, @sha_contenuto);.
        /// </summary>
        internal static string sqlNuovoFile {
            get {
                return ResourceManager.GetString("sqlNuovoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE file SET dim = @dim, t_modifica = @t_modifica, sha_contenuto = @sha_contenuto, valido = @valido WHERE id = @id;.
        /// </summary>
        internal static string sqlSetFileData {
            get {
                return ResourceManager.GetString("sqlSetFileData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table file (
        ///id INTEGER, 
        ///nome_file_c varchar(50) PRIMARY KEY, 
        ///path_relativo_c varchar(100) PRIMARY KEY,
        ///dim int, 
        ///t_modifica DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, t_creazione DATETIME  NOT NULL DEFAULT CURRENT_TIMESTAMP,
        ///sha_contenuto char(128), valido BOOLEAN DEFAULT TRUE);.
        /// </summary>
        internal static string tabellaFile {
            get {
                return ResourceManager.GetString("tabellaFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create table versioni (id_file integer, timestamp_vers datetime NOT NULL DEFAULT CURRENT_TIMESTAMP, PRIMARY KEY (id_file, timestamp_vers), FOREIGN KEY (id_file) REFERENCES file(id) on delete cascade);.
        /// </summary>
        internal static string TabellaVersioni {
            get {
                return ResourceManager.GetString("TabellaVersioni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TRIGGER max_versioni AFTER INSERT ON Versioni FOR EACH ROW BEGIN DELETE FROM Versioni WHERE timestamp_vers = (SELECT MIN(timestamp_vers) FROM Versioni	WHERE id_file = NEW.id_file )	AND id_file IN (SELECT id_file FROM Versioni WHERE id_file = NEW.id_file GROUP BY id_file HAVING COUNT(*) &gt; 3);.
        /// </summary>
        internal static string triggerNumeroVersioni {
            get {
                return ResourceManager.GetString("triggerNumeroVersioni", resourceCulture);
            }
        }
    }
}
